# Generated by Django 3.1.5 on 2021-01-24 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passgen', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='passwords',
            new_name='password',
        ),
    ]
