# Generated by Django 3.1.5 on 2021-01-25 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('passgen', '0002_auto_20210125_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='profile_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
